version: '3.8'
services:
  service1:
    build: ./service1-python
    ports:
      - "5001:5000"

  service2:
    build: ./service2-python
    ports:
      - "5002:5000"
  
  service3:
    build: ./service-java
    ports:
      - "5003:8080"
